# Generated by Django 5.2 on 2025-04-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
