# Generated by Django 5.2 on 2025-04-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0002_alter_product_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='Produto',
        ),
    ]
