# Generated by Django 5.2 on 2025-04-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0003_rename_nome_product_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='produto_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
