# Generated by Django 5.2 on 2025-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0004_remove_product_id_product_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
