# Generated by Django 5.1.3 on 2025-04-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0005_remove_cliente_cpf_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='usuario',
        ),
    ]
