# Generated by Django 5.1.3 on 2025-04-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_manager', '0006_rename_nome_cliente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Produto',
            new_name='produto',
        ),
    ]
